### ISSUE TITLE
Nabla not respecting indention as I would like.

### ISSUE THREAD

**Issue by AndOrangutan** [jbyuki/nabla.nvim#11]
Greetings, I finally got Nabla to work with Neorg (by giving up and coming back to it the next day :p) and have been loving your plugin. I noticed that Nabla doesn't factor in indention outside the first line. I get this isn't a huge issue, especially if you aren't using Neorg or Vimwiki, but I feel like it would be a nice level of polish. 
![Nabla1](https://user-images.githubusercontent.com/40435989/136850050-4c8542d5-9dab-4681-bc8f-8acfc6fa4f61.png)
![Nabla2](https://user-images.githubusercontent.com/40435989/136850055-98407cea-1455-4186-81ac-1e9764525f1e.png)

**Comment by jbyuki** [comment]
Finally, this commit is done. Now it should be possible to
have indented formula with tabulation put in front.
Could you test if it's working?

I guess because we are doing our plugin on spare time (for free), you could get various response to issues ( or no response ). I would not generalize it and interact with repos you like.

**Comment by jbyuki** [comment]
Awesome, something is off with the colors though.
Could you give me the first formula?

**Comment by AndOrangutan** [comment]
Probably has something to do with the fact that I am using it in Neorg or something. Or maybe my theme. Either way, since the original issue is fixed, I will go ahead and close this. Also, could have just typed the equation incorrectly since I am still learning latex.

**Comment by jbyuki** [comment]
Nah, it's an error with my colorization function. I'll fix it in the coming days.
