### ISSUE TITLE
Documentation For Addding Support

### ISSUE THREAD

**Issue by joshpetit** [jbyuki/nabla.nvim#26]
Hey! I think it would help you a lot if you gave us documentation on how to add support for certain latex symbols/equations so you don't have to create everything and people can quickly get up and started in contributing.

I'd be more than happy to contribute some symbols. If it's not tedious enough, having that documentation would be awesome!

**Comment by jbyuki** [comment]
Hi there,
Sorry for the delayed reponse, I've been quite busy with IRL stuff.
I will add more functionnalities to nabla because I also started using it for taking notes (weird, I was not using it before). But I also agree that contributors could make nabla better. See the documentation [here](https://github.com/jbyuki/nabla.nvim/wiki/Add-notation#add-the-new-notation) and if you have any other question regarding extending nabla, I'll be glad to help!

**Comment by joshpetit** [comment]
Awesome stuff! Thank you!
