### ISSUE TITLE
Error: attempt to perform arithmetic on local 'srow' (a nil value)

### ISSUE THREAD

**Issue by tempegarit** [jbyuki/nabla.nvim#31]
Hi! I've just installed this plugin but I couldn't get it  to work. When I pressed `<leader>p`, an error occurred. This was the error message:

```
E5108: Error executing lua ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:730: attempt to perform arithmetic on local 'srow' (a nil value)
stack traceback:
        ...are/nvim/site/pack/packer/start/nabla.nvim/lua/nabla.lua:730: in function 'popup'
        [string ":lua"]:1: in main chunk
```

Expected behavior: An error doesn't occur
Actual behavior: An error occurred

**Comment by tempegarit** [comment]
Sorry my bad. I didn't know that I should put the cursor above an equation. It works now.

**Comment by LeSnake04** [comment]
Maybe display a message explaining how to use the plugin when no katex found.

**Comment by jbyuki** [comment]
Could you explain a bit more what you mean?

**Comment by LeSnake04** [comment]
When a user uses the shortcut and the plugin cannnot find a katex, instead of crashing with this error message, check if srow is nil and if it is display a string on the vim command line (the line where you enter :q etc, no idea how its called) saying something like "To use nable, use this function with the cursor at an equation"

**Comment by jbyuki** [comment]
Thanks for the input @LeSnake04 , this was changed in the last commit.
