### ISSUE TITLE
Support doxygen math blocks 

### ISSUE THREAD

**Issue by aborzunov** [jbyuki/nabla.nvim#6]
**How should the input text representation look like**

```
$\int_0^x y \sin(y) dy $

\f$ \int_0^x y \sin(y) dy \f$
```

**How should the ASCII art output look like**

```
x
∫ ysin(y)dy
0

x
∫ ysin(y)dy
0
```

Detecting or ignoring doxygen math block would be helpful for documenting source code.

Now, if accidentally trigger plugin on doxygen math block it tries to render **all** doxygen math blocks in document (and obviously fails.

https://www.doxygen.nl/manual/formulas.html

**Comment by jbyuki** [comment]
Thank for for posting the issue.

I will probably need a better solution in the long run but I added configurable delimiters in the last commit.
Could you try with the following configuration:

Lua
----

```lua
vim.g.nabla_conceal_inline_match = [[\(^\|[^$]\)\zs\\f\$[^$]\{-1,}\\f\$\ze\($\|[^$]\)]]
vim.g.nabla_inline_delimiter = "\\f$"
```

or

Vim
----

```vim
let g:nabla_conceal_inline_match = "\(^\|[^$]\)\zs\\f\$[^$]\{-1,}\\f\$\ze\($\|[^$]\)"
let g:nabla_inline_delimiter = "\\f$"
```

This will change inline formulas delimiters to the doxygen syntax.

Would it be a viable solution for now? I don't really want to add a per-filetype configuration etc, because I like the simplicity of the plugin.

**Comment by aborzunov** [comment]
Yes, it is nice workaround, thanks! But as a long term feature, it would be nice to have several delimiter types in one document.
